-- Enable UUID extension
create extension if not exists "uuid-ossp";

-- Profiles table (extends auth.users)
create table profiles (
  id uuid references auth.users on delete cascade not null primary key,
  email text not null,
  full_name text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Products table
create table products (
  id uuid default uuid_generate_v4() primary key,
  slug text unique not null,
  title text not null,
  description text,
  price numeric not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Purchases table
create table purchases (
  id uuid default uuid_generate_v4() primary key,
  user_id uuid references profiles(id) on delete cascade not null,
  product_id uuid references products(id) on delete cascade not null,
  status text not null check (status in ('active', 'expired', 'refunded')),
  robokassa_invoice_id text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Videos table
create table videos (
  id uuid default uuid_generate_v4() primary key,
  product_id uuid references products(id) on delete cascade not null,
  title text not null,
  storage_path text not null,
  "order" integer not null default 0,
  duration integer,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Row Level Security (RLS)
alter table profiles enable row level security;
alter table products enable row level security;
alter table purchases enable row level security;
alter table videos enable row level security;

-- RLS Policies

-- Profiles: Users can view and update their own profile
create policy "Users can view own profile"
  on profiles for select
  using ( auth.uid() = id );

create policy "Users can update own profile"
  on profiles for update
  using ( auth.uid() = id );

-- Products: Everyone can view products (public catalog)
create policy "Products are viewable by everyone"
  on products for select
  using ( true );

-- Purchases: Users can view their own purchases
create policy "Users can view own purchases"
  on purchases for select
  using ( auth.uid() = user_id );

-- Videos: Users can view videos if they have an active purchase for the product
create policy "Users can view videos of purchased products"
  on videos for select
  using (
    exists (
      select 1 from purchases
      where purchases.product_id = videos.product_id
      and purchases.user_id = auth.uid()
      and purchases.status = 'active'
    )
  );

-- Storage Policies (bucket 'course-videos')
-- Note: You need to create the bucket 'course-videos' in Supabase Dashboard first and make it Private.

-- Policy to allow authenticated users to download/view files if they purchased the product
-- This is complex to enforce purely on storage level via SQL policies linking to tables easily in all cases,
-- usually we use signed URLs generated on server. 
-- But for basic RLS on storage.objects:
-- (This part usually requires more complex setup or just relying on Signed URLs generated by backend)

-- Initial Data (Example)
insert into products (slug, title, description, price)
values 
  ('formula-movement-level-1', 'Формула Движения. Уровень 1', 'Базовый курс реабилитации', 2950),
  ('formula-movement-level-2', 'Формула Движения. Уровень 2', 'Продвинутый курс реабилитации', 2950);
