name: Deploy to GitHub Pages

on:
  push:
    branches: ["master"]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build with Next.js
        run: npm run build
      
      - name: Create out directory and .nojekyll file
        run: |
          mkdir -p out
          touch out/.nojekyll
      
      - name: Copy CNAME file
        run: |
          if [ -f "CNAME" ]; then
            cp CNAME out/
          elif [ -f "public/CNAME" ]; then
            cp public/CNAME out/
          else
            echo "minenkovrehab.ru" > out/CNAME
          fi
      
      - name: Copy sitemap and robots.txt
        run: |
          if [ -f "public/sitemap.xml" ]; then
            cp public/sitemap.xml out/
          fi
          if [ -f "public/robots.txt" ]; then
            cp public/robots.txt out/
          fi
      
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
          keep_files: false
          force_orphan: true
          commit_message: "Deploy to GitHub Pages [skip ci]"
          full_commit_message: "Deploy to GitHub Pages from commit ${{ github.sha }} [skip ci]" 