name: Deploy to GitHub Pages

on:
  push:
    branches: ["master"]
  # Позволяет запускать workflow вручную из интерфейса Actions
  workflow_dispatch:

# Устанавливаем права для GITHUB_TOKEN, чтобы он мог деплоить на GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

# Позволяет запускать только один деплой и отменяет предыдущие деплои в процессе
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Сборка проекта в статические файлы
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Create .nojekyll file
        run: mkdir -p out && touch out/.nojekyll
      - name: Build with Next.js using force-export
        run: npm run force-export
      - name: Push to gh-pages branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out 