name: Deploy to GitHub Pages

# Добавлен тестовый комментарий для проверки работы Actions
on:
  push:
    branches: ["master"]
  # Позволяет запускать workflow вручную из интерфейса Actions
  workflow_dispatch:

# Устанавливаем права для GITHUB_TOKEN, чтобы он мог деплоить на GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

# Позволяет запускать только один деплой и отменяет предыдущие деплои в процессе
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build with Next.js
        run: npm run build
      
      - name: Export static site
        run: npm run export
      
      - name: List output directory
        run: ls -R out
      
      - name: Create .nojekyll file
        run: |
          mkdir -p out
          touch out/.nojekyll
      
      - name: Copy CNAME file
        run: |
          if [ -f "CNAME" ]; then
            cp CNAME out/
          elif [ -f "public/CNAME" ]; then
            cp public/CNAME out/
          else
            echo "minenkovrehab.ru" > out/CNAME
          fi
      
      - name: Copy sitemap and robots.txt
        run: |
          if [ -f "public/sitemap.xml" ]; then
            cp public/sitemap.xml out/
          fi
          if [ -f "public/robots.txt" ]; then
            cp public/robots.txt out/
          fi
      
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
          publish_branch: gh-pages
          # Не удалять существующие файлы в ветке gh-pages
          keep_files: false
          # Принудительно запушить историю
          force_orphan: true
          # Указать кастомизированное имя коммита
          commit_message: "Deploy to GitHub Pages from master [skip ci]"
          # Включить детальные сообщения о выполнении
          full_commit_message: "Deploy to GitHub Pages from commit ${{ github.sha }} on master [skip ci]" 